/* The following are the benefits of using single-page applications. */

/* 

Caching capabilities. ...
Fast and responsive. ...
Debugging with chrome. ...
Fast development. ...
Enhanced user experience. ...
Conversion to IOS and Android applications. ...
Cross-platform compatibility. ...
Search engine optimization (SEO)

*/